version: '3'

services:

  db:
    image: 'postgres:13.1-alpine'
    restart: always
    container_name: pgsql_banque
    environment:
      POSTGRES_USER : root
      POSTGRES_PASSWORD: root
      POSTGRES_DB : banque
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8083:8080"